Sensor_Nachricht = print(input())
print(f"Ursrünglicher Wert: {Sensor_Nachricht} ", end="  ")
print(f"Typ: {type(Sensor_Nachricht)}")
print(f"Als Integer: {int(Sensor_Nachricht)}", end="  ")
#print(f"Typ: {type(Sensor_Nachricht)}")